version: '3.8'

# 客户合同管理系统 - 外部服务简化部署配置
# 适用于已有MySQL和Redis服务器的环境
# 镜像由GitHub Actions自动构建和推送

services:
  # 应用服务 - 使用外部MySQL和Redis服务器
  app:
    image: ghcr.io/${GITHUB_REPOSITORY:-bluewatercg/projectcontractledger}:${IMAGE_TAG:-latest}
    container_name: contract-ledger-app-simple
    ports:
      - "${FRONTEND_HTTP_PORT:-80}:80"
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      # 应用配置
      - NODE_ENV=${NODE_ENV:-production}
      - BACKEND_PORT=${BACKEND_PORT:-8080}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      
      # 外部MySQL数据库配置
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      
      # 外部Redis配置
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      
      # JWT配置
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      
      # 时区配置
      - TZ=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - app_logs:/var/log/app
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

# 数据卷
volumes:
  app_logs:
    driver: local
