name: Test Build

# 这个工作流用于测试构建，支持所有分支
on:
  push:
    branches: [ '*' ]
  workflow_dispatch:  # 允许手动触发

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: ${{ github.repository }}-backend
  FRONTEND_IMAGE_NAME: ${{ github.repository }}-frontend

jobs:
  test-build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract backend metadata
      id: backend-meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-

    - name: Build backend Docker image (test only)
      uses: docker/build-push-action@v5
      with:
        context: ./apps/backend
        file: ./apps/backend/Dockerfile
        push: false  # 只构建不推送，用于测试
        tags: ${{ steps.backend-meta.outputs.tags }}
        labels: ${{ steps.backend-meta.outputs.labels }}
        cache-from: type=gha,scope=backend
        cache-to: type=gha,mode=max,scope=backend

    - name: Build and push backend image (only for main branches)
      if: contains(fromJson('["main", "master", "develop"]'), github.ref_name)
      uses: docker/build-push-action@v5
      with:
        context: ./apps/backend
        file: ./apps/backend/Dockerfile
        push: true
        tags: ${{ steps.backend-meta.outputs.tags }}
        labels: ${{ steps.backend-meta.outputs.labels }}
        cache-from: type=gha,scope=backend
        cache-to: type=gha,mode=max,scope=backend
        platforms: linux/amd64,linux/arm64

  test-build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract frontend metadata
      id: frontend-meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-

    - name: Build frontend Docker image (test only)
      uses: docker/build-push-action@v5
      with:
        context: ./apps/frontend
        file: ./apps/frontend/Dockerfile
        push: false  # 只构建不推送，用于测试
        tags: ${{ steps.frontend-meta.outputs.tags }}
        labels: ${{ steps.frontend-meta.outputs.labels }}
        cache-from: type=gha,scope=frontend
        cache-to: type=gha,mode=max,scope=frontend

    - name: Build and push frontend image (only for main branches)
      if: contains(fromJson('["main", "master", "develop"]'), github.ref_name)
      uses: docker/build-push-action@v5
      with:
        context: ./apps/frontend
        file: ./apps/frontend/Dockerfile
        push: true
        tags: ${{ steps.frontend-meta.outputs.tags }}
        labels: ${{ steps.frontend-meta.outputs.labels }}
        cache-from: type=gha,scope=frontend
        cache-to: type=gha,mode=max,scope=frontend
        platforms: linux/amd64,linux/arm64

  build-summary:
    needs: [test-build-backend, test-build-frontend]
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Build summary
      run: |
        echo "## 分离式前后端构建摘要" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **后端镜像**: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
        echo "- **前端镜像**: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
        if [[ "${{ contains(fromJson('[\"main\", \"master\", \"develop\"]'), github.ref_name) }}" == "true" ]]; then
          echo "- **Status**: ✅ 构建并推送到镜像仓库" >> $GITHUB_STEP_SUMMARY
        else
          echo "- **Status**: ✅ 构建成功 (仅测试)" >> $GITHUB_STEP_SUMMARY
        fi
